import Container from "../../components/Container";

export default function About(){
    return(
        <Container>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
        </Container>
    )
}